" ========== Vundle Config ==========

filetype off

" Because I can never remember Vundle commands:
"
" :PluginInstall
" :PluginUpdate
" :PluginList
" :PluginClean
" :PluginSearch foo

set rtp+=/usr/local/opt/fzf
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'           " Plugin manager
Plugin 'airblade/vim-gitgutter'         " Displays +/- in gutter
Plugin 'dense-analysis/ale'             " Code linter
Plugin 'itchyny/lightline.vim'          " Fancy modeline
Plugin 'junegunn/fzf.vim'               " Fuzzy finder
Plugin 'rking/ag.vim'                   " Vim plugin for Ag
Plugin 'tpope/vim-fugitive'             " Git blame et al.

" Color schemes
Plugin 'morhetz/gruvbox'
Plugin 'rakr/vim-one'

call vundle#end()
filetype plugin indent on

" ========== General Config ==========

syntax on   " Enable syntax highlighting

set number
set relativenumber
set cursorline

set termguicolors
colorscheme one

set lazyredraw
set ttyfast

set laststatus=2 " Make sure airline is always on
set noshowmode " Don't need showmode when using Airline

set backspace=indent,eol,start " Make backspace behave normally
set wildmenu

" ========== Search Settings ==========

set incsearch   " Search as we type
set hlsearch    " Highlight search results
set nowrapscan  " Stop search at end of file

" ========== Turn off swap files ==========

set noswapfile
set nobackup

" ========== Persistent Undo ==========

set hidden
set undofile
set undodir=~/.vim/undo

" ========== Indentation ==========

set autoindent
set smartindent
set expandtab
set smarttab

set tabstop=4
set shiftwidth=4
set softtabstop=4

set linebreak   " Wrap lines at convenient places

" Show tabs and end of line characters
set listchars=tab:▸\ ,trail:·,nbsp:…
set list

" ========== Split Windows ==========

set splitbelow
set splitright

" ========== Basic Key Mappings ==========

nmap <silent><Leader>[ :bp!<CR>
nmap <silent><Leader>] :bn!<CR>
nmap <silent><Leader>c :let @/ = ""<CR>
nmap <silent><Leader>w :set wrap!<CR>

" Toggle display of invisibles
nmap <silent><Leader>l :set list!<CR>

" FZF
nmap <silent><Leader>p :Files<CR>
nmap <silent><Leader>b :Buffers<CR>
nmap <silent><Leader>t :Tags<CR>
nmap <silent><Leader>r :BTags<CR>

" Git blame
nmap <silent><Leader>g :Gblame!<CR>

" ========== Auto Commands ==========

" Automatically source .vimrc when making changes to it
augroup autosourcing
  au!
  au BufWritePost .vimrc source $MYVIMRC
  au BufWritePost vimrc source $MYVIMRC
augroup END

" ========== Plugin Configuration ==========

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_sizestyle = "H"

let g:lightline = { 'colorscheme': 'one' }

set signcolumn=yes

" Ag.vim
let g:ag_prg="ag -U --ignore .git --ignore tags --vimgrep"

" ========== Allow Local .vimrc ==========

set exrc
set secure
