" ========== Vundle Config ==========

set nocompatible
filetype off

" Because I can never remember Vundle commands:
"
" :PluginInstall
" :PluginList
" :PluginClean
" :PluginSearch foo

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'jwalton512/vim-blade'
Plugin 'pangloss/vim-javascript'
Plugin 'posva/vim-vue'
Plugin 'rking/ag.vim'
Plugin 'rstacruz/sparkup'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

Plugin 'chriskempson/vim-tomorrow-theme'
Plugin 'NLKNguyen/papercolor-theme'

call vundle#end()
filetype plugin indent on

" ========== General Config ==========

syntax on   " Enable syntax highlighting

set number
set relativenumber

colorscheme Tomorrow-Night

set lazyredraw
set ttyfast

" Disable Background Color Erase so things play nice in tmux
if &term =~ '256color'
  set t_ut=
endif

set laststatus=2 " Make sure airline is always on
set noshowmode " Don't need showmode when using Airline

set backspace=indent,eol,start " Make backspace behave normally
set wildmenu

" ========== Search Settings ==========

set incsearch   " Search as we type
set hlsearch    " Highlight search results
set nowrapscan  " Stop search at end of file

" ========== Turn off swap files ==========

set noswapfile
set nobackup

" ========== Persistent Undo ==========

set hidden

" ========== Indentation ==========

set autoindent
set smartindent
set expandtab
set smarttab

set tabstop=4
set shiftwidth=4
set softtabstop=4

set linebreak   " Wrap lines at convenient places

" Show tabs and end of line characters
" set listchars=tab:▸\ ,space:·,trail:·,nbsp:…,eol:↵
set listchars=tab:▸\ ,trail:·,nbsp:…
set list

hi NonText ctermfg=243
hi SpecialKey ctermfg=243
hi LineNr ctermfg=8

" ========== Split Windows ==========

set splitbelow
set splitright

" ========== FileType Specific Indentations  ==========

" Not yet implemented but, rather than using ~/.vim/after/ftplugin, autocmd
" can be used. For example:
"
" autocmd FileType yaml setlocal ts=2 sw=2 sts=2 expandtab
"
" Also, coerce extensions into certain filetypes:
"
" autocmd BufNewFile,BufRead *.ctp setfiletype php

augroup syntaxhighlighting
  au!
  au BufRead,BufNewFile *.twig set filetype=htmljinja
augroup END

" ========== Auto Commands ==========

" Automatically source .vimrc when making changes to it
augroup autosourcing
  au!
  au BufWritePost .vimrc source $MYVIMRC
  au BufWritePost vimrc source $MYVIMRC
augroup END

" ========== Plugin Configuration ==========

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_sizestyle = "H"

" Load Powerline fonts
let g:airline_powerline_fonts = 1
let g:airline_theme = 'tomorrow'

" Enable buffer bar
let g:airline#extensions#tabline#enabled = 1

let g:gitgutter_sign_column_always = 1

" Gives a nice performance boost to CtrlP
let g:ctrlp_use_cache = 1
let g:ctrlp_clear_cache_on_exit = 0

" ========== Basic Key Mappings ==========

inoremap jj <ESC>

nmap <silent><Leader>[ :bp!<CR>
nmap <silent><Leader>] :bn!<CR>
nmap <silent><Leader>c :let @/ = ""<CR>
nmap <silent><Leader>s :SyntasticToggleMode<CR>

" Toggle display of invisibles
nmap <silent><Leader>l :set list!<CR>
nmap <silent><Leader>w :set wrap!<CR>

" ========== Allow Local .vimrc ==========

set exrc
set secure
